[package]
name = "webauthexp"
version = "0.1.0"
authors = ["SAWADA Tadashi <cesare@mayverse.jp>"]
edition = "2018"

[[bin]]
name = "webauthexp"
path = "src/webauthexp.rs"

[dependencies]
actix-rt = "~2.2.0"
actix-web = "=4.0.0-beta.3"
actix-http = "=3.0.0-beta.3"
actix-utils = "=3.0.0-beta.2"
anyhow = "~1.0.40"
tokio = { version = "~1.4.0", features = ["macros", "rt-multi-thread"] }
