[server]
bind = "127.0.0.1"
port = 8080

[github]
client_id = "YOUR-GITHUB-CLIENT-ID"
client_secret = "YOUR-GITHUB-CLIENT-SECRET"
redirect_uri = "http://localhost:8080/github/callback"
scope = "read:user"

[google]
client_id = "YOUR-GOOGLE-CLIENT-ID"
client_secret = "YOUR-GOOGLE-CLIENT-SECRET"
redirect_uri = "http://localhost:8080/google/callback"
scope = "openid email"

[spotify]
client_id = "YOUR-SPOTIFY-CLIENT-ID"
redirect_uri = "http://localhost:8080/spotify/callback"
scope = "user-library-read user-read-email"  # see https://developer.spotify.com/documentation/general/guides/scopes/ for available scopes
